spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    url: jdbc:postgresql://localhost:5432/paddocca
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop